[package]
name = "web"
version = "0.1.0"
edition = "2024"

[dependencies]
yew = { version = "0.22", features = ["csr"] }
reqwasm = "0.5"
wasm-bindgen-futures = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
wasm-logger = "0.2"
web-sys = "0.3"
