[package]
name = "bank"
version = "0.7.0"
edition = "2024"

[dependencies]
macros = { path = "../macros" }
regex = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
tempfile = "3.23.0"
