[package]
name = "processor"
version = "0.1.0"
edition = "2024"

[dependencies]
libloading = "0.9"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
image = { workspace = true }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
