[package]
name = "plugin_blur"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
image = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
