[package]
name = "bank-system"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.0.1", features = [
    "add",
    "add_assign",
    "mul",
    "mul_assign",
    "from",
    "into",
] }
