[package]
name = "parsers"
version = "0.5.0"
edition = "2024"

[dependencies]
bank = { path = "../bank" }
csv = "1"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
assert_matches = { workspace = true }
