[workspace]
resolver = "3"
members = ["backend", "exchange"]

[workspace.dependencies]
rand = "0.9"
log = "0.4"
env_logger = "0.11"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.49", features = ["full"] }
futures = "0.3"
